name: Deploy and Release Plugin
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '22'
      - name: Build
        run: |
          npm ci
          npm run start
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
